### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SivilTaram**
Thanks for the awesome paper list of reasoning! The paper of Pi et al. 2022 also investigates on the reasoning capabilities of language models by designing new pre-training objective functions.

### CODE REVIEW

**Comment by SivilTaram** [comment]
@jeffhj Feel free to leave comments if there is any problem

**Comment by jeffhj** [comment]
Hi @SivilTaram, thanks for your pull request!

I am very busy this week. I will read the paper and deal with the pull request next week.
(Since I need to make sure the categorization is correct :)

**Comment by jeffhj** [comment]
Read the paper. Good work!

**Comment by SivilTaram** [comment]
@jeffhj Thanks for the kind words! Great survey!

**Pull request merged**
