### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by huybery**

### CODE REVIEW

**Comment by jeffhj** [comment]
Will read the paper later.

Question: why not cite our survey (if you know it and think it is useful)? lol

**Comment by huybery** [comment]
😂 Sorry for my oversight, I just found your survey today and I will be citing the paper in the next version of arxiv.

**Comment by jeffhj** [comment]
haha, just kidding

I will take some time to read this paper later :)
(since I need to make sure the categorization is correct)

**Comment by huybery** [comment]
Thank you for your hard work! A very comprehensive and useful survey, i like it :)

**Pull request merged**
